### ISSUE TITLE
the update does not work

### ISSUE THREAD

**Issue by sluchznak** [Insolita/yii2-simplerbac#4]
The update roles and permissions does not work. Element already exist.

**Comment by Insolita** [comment]
all works http://yii2redis-insolita1.c9.io/ru/simplerbac/default/index.html update again

**Comment by sluchznak** [comment]
![2015-03-28 21 07 55](https://cloud.githubusercontent.com/assets/4091442/6881747/8be8cf8a-d58e-11e4-8d35-200261c2925f.png)
